### ISSUE TITLE
Should option checkboxes (light, medium, full) be radio buttons?

### ISSUE THREAD

**Issue by leonie12** [Nicola1971/EvoBackup#10]
At the moment it is possible to select two or all three options at once. Although I don't know how this is handled internally I would expect that if I choose one option that then the other two options are cleared. Wouldn't radio buttons be the better element to choose these options?

**Comment by Nicola1971** [comment]
yes it's an actual limit/issue of the module. does not work with radio buttons- so you need to select/unselect checkbox.

thinking about replace with toggle switch for a better logic of use (on/off)

**Comment by Nicola1971** [comment]
fixed in latest pull. 
video: https://youtu.be/w_tsLR0ggfY
