### ISSUE TITLE
Error : fread(): Length parameter must be greater than 0

### ISSUE THREAD

**Issue by leonie12** [Nicola1971/EvoBackup#13]
EvoBackup 1.3, Evo 1.3.4, Full Backup: No archive created. Instead error message:

> Error information 	
ErrorType[num] 	WARNING[2]
File 	/assets/modules/evobackup/pclzip.lib.php
Line 	2677
Source 	EvoBackup - Module

> Benchmarks 	
MySQL 	0.0089 s (3 Requests)
PHP 	18.2077 s
Total 	18.2166 s
Memory 	29.993507385254 mb

> Backtrace
include_once(string $var1)
manager/index.php on line 606
evalModule(string $var1, array $var2)
manager/processors/execute_module.processor.php on line 60

**Comment by Nicola1971** [comment]
PHP7?

seems this old issue https://github.com/Nicola1971/EvoBackup/issues/9

**Comment by leonie12** [comment]
PHP7.1.2.

I knew that I had seen this error somewhere ;-) but could not find the issue on github. Seems to be the same error.
Error happens also with memory increased to 250M and time limit to 500.
Created archive is about 130 Mb and seems to contain all files. Only db is missing.

**Comment by Nicola1971** [comment]
@leonie12 tested with PHP 7.1.0 and PHP 7.1.8 can't replicate the issue.

maybe you have not much space for the full backup?

please try: 
- fullbackup - only files **without DB backup**
- Only DB backup

**Comment by Nicola1971** [comment]
tested with PHP 7.1.2 again no issue with fullbackup

**Comment by leonie12** [comment]
Backup database only:

> « MODX Parse Error »
Error : set_time_limit() has been disabled for security reasons
Error information 	
ErrorType[num] 	WARNING[2]
File 	/home/webnfakmm/html/baumpflege/assets/modules/evobackup/evobackup.php
Line 	366
Source 	EvoBackup - Module

> Benchmarks 	
MySQL 	0.0026 s (3 Requests)
PHP 	0.1242 s
Total 	0.1268 s
Memory 	5.647087097168 mb

> Backtrace
include_once(string $var1)
manager/index.php on line 606
evalModule(string $var1, array $var2)
manager/processors/execute_module.processor.php on line 60



Full backup files without db:

ZIP-Archive with all (as far as I can see) files is created but error thrown:

> « MODX Parse Error »
Error : fread(): Length parameter must be greater than 0
Error information 	
ErrorType[num] 	WARNING[2]
File 	/home/webnfakmm/html/baumpflege/assets/modules/evobackup/pclzip.lib.php
Line 	2677

> Benchmarks 	
MySQL 	0.0078 s (3 Requests)
PHP 	17.2408 s
Total 	17.2486 s
Memory 	29.994590759277 mb

> Backtrace
include_once(string $var1)
manager/index.php on line 606
evalModule(string $var1, array $var2)
manager/processors/execute_module.processor.php on line 60


Database backup from Evo core backup functionality is no problem.

The errors happen with different installs only on live server. Local lampp works as expected.

**Comment by Nicola1971** [comment]
so, is not something related to EvoBackup or PHP version, but to your server configuration:
> Error : set_time_limit() has been disabled for security reasons

(to prevent from running long processes that could impact on the server) 

Solution:
1) Remove the set_time_limit string from the disable_functions at php.ini* file
or
Ask your hosting provider to remove the string above if you don't have an access to the php.ini* file

2) Comment lines:

https://github.com/Nicola1971/EvoBackup/blob/1b83ba1304c91b81865ca0053958a6e4f49a5739/assets/modules/evobackup/evobackup.php#L335

https://github.com/Nicola1971/EvoBackup/blob/1b83ba1304c91b81865ca0053958a6e4f49a5739/assets/modules/evobackup/evobackup.php#L366

https://github.com/Nicola1971/EvoBackup/blob/1b83ba1304c91b81865ca0053958a6e4f49a5739/assets/modules/evobackup/evobackup.php#L402

https://github.com/Nicola1971/EvoBackup/blob/1b83ba1304c91b81865ca0053958a6e4f49a5739/assets/modules/evobackup/evobackup.php#L427

**Comment by leonie12** [comment]
Solutions 1 not possible here.
Solution 2 (commenting "@set_time_limit()") works.

Backup archives with db included are created as expected. 

On one install I get the message "Backup created succesfull". But when trying to download the created file I get the error message "File not found" even though it exists in the right path. Retrying delivers the error message "Something went wrong".
Downloading this backup archive via FTP is no problem.
