### ISSUE TITLE
There are no folders assets/flash and assets/media and index-ajax.php in Evolution

### ISSUE THREAD

**Issue by webber12** [Nicola1971/EvoBackup#14]
That folders and file where removed in modern evo https://github.com/evolution-cms/evolution, and occures errors when they are choosen in module
https://github.com/Nicola1971/EvoBackup/blob/c1997c8fd833909f3d21174c3c0dcba44e1bd4ac/assets/modules/evobackup/evobackup.php#L565
https://github.com/Nicola1971/EvoBackup/blob/c1997c8fd833909f3d21174c3c0dcba44e1bd4ac/assets/modules/evobackup/evobackup.php#L567
https://github.com/Nicola1971/EvoBackup/blob/c1997c8fd833909f3d21174c3c0dcba44e1bd4ac/assets/modules/evobackup/evobackup.php#L616

**Comment by Nicola1971** [comment]
Thanks.
Just removed in last update :)
