### ISSUE TITLE
Spanish lang. file

### ISSUE THREAD

**Issue by risingisland** [Nicola1971/EvoBackup#5]
Spanish lang. file... 
[spanish.zip](https://github.com/Nicola1971/EvoBackup/files/690087/spanish.zip)

**Comment by Nicola1971** [comment]
Thanks!

**Comment by Nicola1971** [comment]
@risingisland requires some updates for RC3

https://github.com/Nicola1971/EvoBackup

https://github.com/Nicola1971/EvoBackup/blob/master/assets/modules/evobackup/lang/spanish.php#L35-L37

https://github.com/Nicola1971/EvoBackup/blob/master/assets/modules/evobackup/lang/spanish.php#L73-L98

**Comment by risingisland** [comment]
Updated...
[spanish.zip](https://github.com/Nicola1971/EvoBackup/files/690657/spanish.zip)

**Comment by Nicola1971** [comment]
Re updated - I  hope this is the last languages update

https://github.com/Nicola1971/EvoBackup/commit/c69045f70ba45e8c92ced1afc9632ca97be9c212

https://github.com/Nicola1971/EvoBackup/commit/698edfd147ad1dcb848cc103b4a497c724b3bc78

**Comment by risingisland** [comment]
File: display.php
Line: 51
Contains hard-coded word "Close"

**Comment by risingisland** [comment]
Just received this error while preforming a backup?
Memory issue?
![evobackup](https://cloud.githubusercontent.com/assets/6113504/21732834/6a73565c-d453-11e6-9e2c-b70049cc3886.png)

**Comment by Nicola1971** [comment]
probably - try increase memory or a smaller zip

zip stopped with a temp file?

**Comment by Nicola1971** [comment]
fixed close button

**Comment by risingisland** [comment]
Updated:
[spanish.zip](https://github.com/Nicola1971/EvoBackup/files/690868/spanish.zip)

**Comment by Nicola1971** [comment]
https://github.com/Nicola1971/EvoBackup/commit/9c50b88c8ba8662d60abd9739efe1c9a4c6baa1e
