### ISSUE TITLE
RC3 DEV

### ISSUE THREAD

**Issue by Nicola1971** [Nicola1971/EvoBackup#6]
Need Help in testing:
https://github.com/Nicola1971/EvoBackup

# New in RC3:

* Restore Sql backup Button
* Extract Archive Backup Button
* New Alerts for Delete, Restore and Extract 
* New language strings for restore, extract, alerts (not just an _Are you sure?_  text)
* More Help informations in Archive tab and sql tab (taken from alert language strings)
* Moved styles to a .css file

# To do:
* tests
* fix issue https://github.com/Nicola1971/EvoBackup/issues/3

@fourroses666 and @risingisland , you can find new english untraslated stings in your language files

![wuz62cxjw7gaaaaaelftksuqmcc](https://cloud.githubusercontent.com/assets/7342798/21722852/a61e41aa-d42e-11e6-8989-ed2f63b60911.png)

![0aygaaaabjru5erkjggg](https://cloud.githubusercontent.com/assets/7342798/21722817/882eddbc-d42e-11e6-9320-abc722caa428.png)

![download](https://cloud.githubusercontent.com/assets/7342798/21722820/8c0fd620-d42e-11e6-8b18-7a67d8fa7855.png)

**Comment by fourroses666** [comment]
Hi Nicola, I don't see new strings :o

**Comment by Nicola1971** [comment]
@fourroses666  sorry , forgot to said RC3 is in dev branch
https://github.com/Nicola1971/EvoBackup/tree/dev



New strings for nederlands RC3 
(just added 3 more strings for alerts translation)

here: https://github.com/Nicola1971/EvoBackup/blob/dev/assets/modules/evobackup/lang/nederlands.php#L37-L38

and here: https://github.com/Nicola1971/EvoBackup/blob/dev/assets/modules/evobackup/lang/nederlands.php#L87-L99

**Comment by fourroses666** [comment]
Ok done! Could have figured it out

**Comment by Nicola1971** [comment]
moved to master

**Comment by Nicola1971** [comment]
I think this is the last RC

Fixed a lot of issue add all things i can :)

**Comment by Nicola1971** [comment]
RC3 is closed - ready for PL
