### ISSUE TITLE
Default Backup type:  Light or Medium?

### ISSUE THREAD

**Issue by Nicola1971** [Nicola1971/EvoBackup#8]
Default Backup type:  Light or Medium?

**Comment by fourroses666** [comment]
Full 😆

**Comment by Nicola1971** [comment]
to kill server space to all??  😆

**Comment by fourroses666** [comment]
Hmm for cron its not that wise. Then maybe light/small. When I make a backup I need the full version. But for cron backups probably light/small will do.

**Comment by Nicola1971** [comment]
Don't know much about cron, maybe will be better doing with [AutoEvoBackup](https://github.com/Nicola1971/AutoEvoBackup)

Anyway, the lighter backup it's better for users and for a fast and secure backup (ie: for support hacked users), without the risk of kill server space and memory on a small server (bigger zip > more memory required)

Plus:

* config.inc.php should be better only in full backup?
* robot.txt?
