### ISSUE TITLE
RC3: error and no db dump with medium and full site backup – Error : fread(): Length parameter must be greater than 0

### ISSUE THREAD

**Issue by leonie12** [Nicola1971/EvoBackup#9]
![evobackup_error](https://cloud.githubusercontent.com/assets/24967436/21736140/ca72ab1e-d46e-11e6-91ed-c99f5edbc4f9.jpg)
When using medium backup or full site backup (each with "include db" checked) I get the following error:
"Error : fread(): Length parameter must be greater than 0" (see screenshot). The zip file with the desired folders is produced but no db included.
Light backup works as expected.
This happens on the live server and on my local machine.

**Comment by Nicola1971** [comment]
it's a memory error-
this is the reason why i rewritten the original module.

creating a zip with a complete backup requires a lot of resources (greater archive > greater memory usage):
solution:
1) allow users to change memory settings in module settings.
2) allow users to select only most required files

so: change memory / zip settings or choose a lighter backup

**Comment by Nicola1971** [comment]
just for confirm: backup stops with a temp file near 50mb?

**Comment by Nicola1971** [comment]
just for confirm: backup stops with a temp file near 50mb?

go to manage files and delete temp file

increase memory zip to 60-70 or 80 and retry

**Comment by leonie12** [comment]
Backup completes as far as I have checked the whole zip with the expected name and all files included. Just the db is not included. This happens even when I raise the memory and zip limit to 500 in the module settings. I don't know if this changes something on the server..
It throws the error after six to seven seconds.
Neither db nor files are of big size.

**Comment by Nicola1971** [comment]
actually i can't replicate the issue.

does it happen on a localhost too?

**Comment by leonie12** [comment]
It also happens on a local lammp stack. Same behaviour. Live with evo1.2. Local Evo 1.2.1 RC.

**Comment by Nicola1971** [comment]
edit: i can replicate :) - it's related to one of my latest commits - i wil revert tomorrow from my main pc ;)

**Comment by Nicola1971** [comment]
seems fixed to me - try to install latest package

**Comment by leonie12** [comment]
Sorry, no change at all. Same error.

**Comment by Nicola1971** [comment]
have you reinstalled? updated the module code?

**Comment by Nicola1971** [comment]
just done a full backup of one of my sites: 170mb of zip archive - no issue

**Comment by leonie12** [comment]
Tested extensively. However: Same behaviour and error.
I deleted folder evobackup and uploaded new with current evobackup-master. Then deleted module and installed new module with current EvoBackup.tpl. Backup light is working as expected, medium and full throw the known error and produce the zip archive with all chosen files but without db included.

**Comment by Nicola1971** [comment]
can you send me access to one of those sites?

**Comment by Nicola1971** [comment]
do you use package manager to install the module?

**Comment by leonie12** [comment]
I tested some more. On local XAMPP the error happens all the time when using medium or full. On production server (not the best idea for testing …) it works most times.

One additional issue seems to be that depending of the order in which you tick the checkboxes for backup type there are different selections. If you uncheck light first and then check full you get another result than if you check full first and then uncheck light.
The error results also when checking no backup type and only checking some files to backup.

First I installed manually. But also after using package manager: no difference.

**Comment by Nicola1971** [comment]
i'm trying everything > full, medium, all checked - nothing

**Comment by leonie12** [comment]
I installed it on a different website with completely different configuration on lacal XAMPP and the error happens as before.

**Comment by leonie12** [comment]
To get closer to the problem I installed the module via package manager on one more production website. The only option that is working is light backup. Everything else throws an error identical to the screenshot above.
All tested websites have zip-archives between 40 and 70 MB for full backup. Nothing big.
Everywhere php7.

**Comment by Nicola1971** [comment]
i use 80M of memory for full backup on very small site.

try to increase to 80M or 100M in module config:
* ZIP memory limit:
*DB memory limit:

**Before of that** update again the module, i've just updated pclzip from 2.4 to 2.8.2 (should have better performance)

**Comment by leonie12** [comment]
I downloaded new master, installed via package manager (on one local and one production server) and tested with ZIP memory limit: 500M and DB memory limit:500M.
Result is the same as before. Now the error happens in line 2673 of pclzip.lib.php.

Benchmarks 	
MySQL 	0.0042 s (5 Requests)
PHP 	10.5379 s
Total 	10.5421 s
Memory 	23.550674438477 mb

The error does not seem to have to do with memory limit because in my case the zip files are completely created just without db included. And that by using only a small amount of memory. The problem seems somehow the inclusion of the db. Is there a difference between light and medium, full backup?

**Comment by Nicola1971** [comment]
Not in db inclusion.. Run after zip files and add sql to zip.

**Comment by Nicola1971** [comment]
PHP version?

**Comment by leonie12** [comment]
See above: Everything PHP 7 for me.

**Comment by Nicola1971** [comment]
maybe related to php7, because 've installed and i'm using EvoBackup on about 12 live sites on 3 different servers (all php 5x) and no issue at all

**Comment by Nicola1971** [comment]
only one site had issue with this module - caused by an .htaccess in assets folder

**Comment by leonie12** [comment]
I can confirm that it works with php 5.6.4 but throws reproducible above error with php 7.0.11.

**Comment by Nicola1971** [comment]
i don't have a live server with php7, so i installed wAmp (portable multi php wamp) on my local machine:

* Tested with Php 7.0.3 - no errors
* Tested with Php 7.0.14 - no errors
* Tested with Php 7.1.0 - no errors

**Comment by Nicola1971** [comment]
i've set "show all errors" in evo system and found a couple of deprecated in php7.1

added some fixes to pclzip libary and dupsql funcion, for  deprecated constructor in PHP7

Now i really cant find other issues, please try the latest build

**Comment by leonie12** [comment]
I tested on different installations with php7:
 Production server PHP 7.0.11, local lampp PHP 7.0.9. All with said error.

Am 11.01.2017 um 12:32 schrieb Nicola:
> i don't have a live server with php7, so i installed wAmp (portable multi php wamp) on my local machine:
> 
> * Tested with Php 7.0.3 - no errors
> * Tested with Php 7.0.14 - no errors
> * Tested with Php 7.1.0 - no errors
>

**Comment by Nicola1971** [comment]
please try latest build

i'm installing PHP 7.0.11 and PHP 7.0.9

**Comment by Nicola1971** [comment]
Tested latest build with PHP 7.0.11 and PHP 7.0.9 - **no errors** with medium or full backups

**Comment by leonie12** [comment]
Gratulation. It seems that you got it fixed :-) . No more errors for me.

**Comment by Nicola1971** [comment]
oh yeah!!
